apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: tgjhuijbers/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-custer-ip-service
            - name: REDIS_PORT
              value: '6379'
      
---
#next entry